service: chromium

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage}
  region: us-east-1

layers:
  chromium:
    name: chromium
    package:
      artifact: layer.zip
    compatibleRuntimes:
      - nodejs20.x
      - nodejs18.x
      - nodejs16.x
    compatibleArchitectures:
      - x86_64
